import { Submission } from "./submissions.types";

export const mockSubmissions: Submission[] = [
  {
    Submission_ID: 1,
    Stud_ID: 1,
    Student_Name: "Ahmed Hassan",
    Track_ID: 1,
    Track_Name: "Computer Science",
    Course_ID: 1,
    Course_Name: "Operating Systems",
    Exam_ID: 1,
    Exam_Title: "Midterm Exam",
    Exam_Duration_Minutes: 60,
    Grade: 85.5,
    Attempt_No: 2,
    Max_Attempt: 3,
    Submit_Date: "2026-02-05T10:30:00",
    Taken_Date: "2026-02-05T09:32:00",
    Time_Taken_Minutes: 58,
    Status: "Submitted",
  },
  {
    Submission_ID: 2,
    Stud_ID: 2,
    Student_Name: "Fatima Mohammed",
    Track_ID: 1,
    Track_Name: "Computer Science",
    Course_ID: 2,
    Course_Name: "Data Structures",
    Exam_ID: 3,
    Exam_Title: "Final Prep",
    Exam_Duration_Minutes: 90,
    Grade: 92.0,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: "2026-02-07T14:15:00",
    Taken_Date: "2026-02-07T12:30:00",
    Time_Taken_Minutes: 85,
    Status: "Submitted",
  },
  {
    Submission_ID: 3,
    Stud_ID: 3,
    Student_Name: "Omar Khaled",
    Track_ID: 1,
    Track_Name: "Computer Science",
    Course_ID: 3,
    Course_Name: "Algorithms",
    Exam_ID: 4,
    Exam_Title: "Quiz 1",
    Exam_Duration_Minutes: 30,
    Grade: 68.0,
    Attempt_No: 3,
    Max_Attempt: 3,
    Submit_Date: "2026-02-06T09:00:00",
    Taken_Date: "2026-02-06T08:35:00",
    Time_Taken_Minutes: 25,
    Status: "Submitted",
  },
  {
    Submission_ID: 4,
    Stud_ID: 4,
    Student_Name: "Maryam Ali",
    Track_ID: 2,
    Track_Name: "Data Science",
    Course_ID: 4,
    Course_Name: "Databases",
    Exam_ID: 5,
    Exam_Title: "Midterm Exam",
    Exam_Duration_Minutes: 60,
    Grade: 78.5,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: "2026-02-04T11:00:00",
    Taken_Date: "2026-02-04T10:05:00",
    Time_Taken_Minutes: 55,
    Status: "Submitted",
  },
  {
    Submission_ID: 5,
    Stud_ID: 5,
    Student_Name: "Youssef Ibrahim",
    Track_ID: 3,
    Track_Name: "Web Development",
    Course_ID: 5,
    Course_Name: "Web Dev Fundamentals",
    Exam_ID: 6,
    Exam_Title: "Final Exam",
    Exam_Duration_Minutes: 120,
    Grade: 95.0,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: "2026-02-08T15:00:00",
    Taken_Date: "2026-02-08T13:10:00",
    Time_Taken_Minutes: 110,
    Status: "Submitted",
  },
  {
    Submission_ID: 6,
    Stud_ID: 6,
    Student_Name: "Layla Ahmed",
    Track_ID: 2,
    Track_Name: "Data Science",
    Course_ID: 4,
    Course_Name: "Databases",
    Exam_ID: 5,
    Exam_Title: "Midterm Exam",
    Exam_Duration_Minutes: 60,
    Grade: 55.0,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: "2026-02-04T11:10:00",
    Taken_Date: "2026-02-04T10:15:00",
    Time_Taken_Minutes: 55,
    Status: "Submitted",
  },
  {
    Submission_ID: 7,
    Stud_ID: 7,
    Student_Name: "Hassan Mostafa",
    Track_ID: 1,
    Track_Name: "Computer Science",
    Course_ID: 1,
    Course_Name: "Operating Systems",
    Exam_ID: 1,
    Exam_Title: "Midterm Exam",
    Exam_Duration_Minutes: 60,
    Grade: null,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: null,
    Taken_Date: "2026-02-08T10:00:00",
    Time_Taken_Minutes: null,
    Status: "In Progress",
  },
  {
    Submission_ID: 8,
    Stud_ID: 8,
    Student_Name: "Nour El-Din",
    Track_ID: 3,
    Track_Name: "Web Development",
    Course_ID: 5,
    Course_Name: "Web Dev Fundamentals",
    Exam_ID: 6,
    Exam_Title: "Final Exam",
    Exam_Duration_Minutes: 120,
    Grade: 88.0,
    Attempt_No: 2,
    Max_Attempt: 3,
    Submit_Date: "2026-02-08T16:00:00",
    Taken_Date: "2026-02-08T14:05:00",
    Time_Taken_Minutes: 115,
    Status: "Submitted",
  },
  {
    Submission_ID: 9,
    Stud_ID: 9,
    Student_Name: "Salma Yasser",
    Track_ID: 2,
    Track_Name: "Data Science",
    Course_ID: 2,
    Course_Name: "Data Structures",
    Exam_ID: 3,
    Exam_Title: "Final Prep",
    Exam_Duration_Minutes: 90,
    Grade: 72.0,
    Attempt_No: 2,
    Max_Attempt: 3,
    Submit_Date: "2026-02-07T15:00:00",
    Taken_Date: "2026-02-07T13:40:00",
    Time_Taken_Minutes: 80,
    Status: "Submitted",
  },
  {
    Submission_ID: 10,
    Stud_ID: 10,
    Student_Name: "Karim Adel",
    Track_ID: 1,
    Track_Name: "Computer Science",
    Course_ID: 3,
    Course_Name: "Algorithms",
    Exam_ID: 4,
    Exam_Title: "Quiz 1",
    Exam_Duration_Minutes: 30,
    Grade: 100.0,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: "2026-02-06T09:15:00",
    Taken_Date: "2026-02-06T08:50:00",
    Time_Taken_Minutes: 25,
    Status: "Submitted",
  },
  {
    Submission_ID: 11,
    Stud_ID: 1,
    Student_Name: "Ahmed Hassan",
    Track_ID: 1,
    Track_Name: "Computer Science",
    Course_ID: 2,
    Course_Name: "Data Structures",
    Exam_ID: 3,
    Exam_Title: "Final Prep",
    Exam_Duration_Minutes: 90,
    Grade: 65.0,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: "2026-02-01T10:00:00",
    Taken_Date: "2026-02-01T08:35:00",
    Time_Taken_Minutes: 85,
    Status: "Submitted",
  },
  {
    Submission_ID: 12,
    Stud_ID: 4,
    Student_Name: "Maryam Ali",
    Track_ID: 2,
    Track_Name: "Data Science",
    Course_ID: 5,
    Course_Name: "Web Dev Fundamentals",
    Exam_ID: 6,
    Exam_Title: "Final Exam",
    Exam_Duration_Minutes: 120,
    Grade: null,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: null,
    Taken_Date: "2026-02-08T18:00:00",
    Time_Taken_Minutes: null,
    Status: "In Progress",
  },
  {
    Submission_ID: 13,
    Stud_ID: 11,
    Student_Name: "Rana Ehab",
    Track_ID: 3,
    Track_Name: "Web Development",
    Course_ID: 1,
    Course_Name: "Operating Systems",
    Exam_ID: 1,
    Exam_Title: "Midterm Exam",
    Exam_Duration_Minutes: 60,
    Grade: 45.0,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: "2026-02-05T11:00:00",
    Taken_Date: "2026-02-05T10:05:00",
    Time_Taken_Minutes: 55,
    Status: "Submitted",
  },
  {
    Submission_ID: 14,
    Stud_ID: 12,
    Student_Name: "Khaled Wael",
    Track_ID: 1,
    Track_Name: "Computer Science",
    Course_ID: 2,
    Course_Name: "Data Structures",
    Exam_ID: 3,
    Exam_Title: "Final Prep",
    Exam_Duration_Minutes: 90,
    Grade: 82.0,
    Attempt_No: 3,
    Max_Attempt: 3,
    Submit_Date: "2026-02-07T16:00:00",
    Taken_Date: "2026-02-07T14:40:00",
    Time_Taken_Minutes: 80,
    Status: "Submitted",
  },
  {
    Submission_ID: 15,
    Stud_ID: 13,
    Student_Name: "Mona Zakaria",
    Track_ID: 2,
    Track_Name: "Data Science",
    Course_ID: 3,
    Course_Name: "Algorithms",
    Exam_ID: 4,
    Exam_Title: "Quiz 1",
    Exam_Duration_Minutes: 30,
    Grade: 98.0,
    Attempt_No: 1,
    Max_Attempt: 3,
    Submit_Date: "2026-02-06T09:30:00",
    Taken_Date: "2026-02-06T09:05:00",
    Time_Taken_Minutes: 25,
    Status: "Submitted",
  }
];
