import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo, useState } from "react";
const CourseCard = ({ course }) => {
    const [expanded, setExpanded] = useState(false);
    const [showPopover, setShowPopover] = useState(false);
    const topics = course.Topics;
    const visibleTopics = useMemo(() => (expanded ? topics : topics.slice(0, 3)), [expanded, topics]);
    const remainingCount = Math.max(0, topics.length - visibleTopics.length);
    return (_jsxs("div", { className: "course-card", children: [_jsx("h3", { className: "course-card-title", children: course.Course_Name }), _jsx("div", { className: "course-card-track", children: _jsx("span", { className: "course-track-badge", children: course.Track_Name }) }), _jsxs("div", { className: "course-card-stats", children: [_jsxs("div", { className: "course-stat", children: [_jsx("span", { className: "course-stat-value", children: course.Students_Count }), _jsx("span", { className: "course-stat-label", children: "Students" })] }), _jsxs("div", { className: "course-stat", children: [_jsx("span", { className: "course-stat-value", children: course.Exams_Count }), _jsx("span", { className: "course-stat-label", children: "Exams" })] }), _jsxs("div", { className: "course-stat", children: [_jsx("span", { className: "course-stat-value", children: course.Max_Attempt }), _jsx("span", { className: "course-stat-label", children: "Attempts" })] }), _jsxs("div", { className: "course-stat", children: [_jsxs("span", { className: "course-stat-value", children: [course.Passing_Grade, "%"] }), _jsx("span", { className: "course-stat-label", children: "Passing Grade" })] })] }), _jsxs("div", { className: `course-card-topics ${expanded ? "topics-expanded" : "topics-collapsed"}`, style: { position: "relative", display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 16 }, children: [visibleTopics.map((t, idx) => (_jsx("span", { className: "course-track-badge topic-pill", style: { animationDelay: expanded ? `${idx * 60}ms` : "0ms" }, children: t.Topic_Name }, t.Topic_ID))), remainingCount > 0 && !expanded && (_jsxs("span", { className: "course-last-updated topics-view-all", onClick: () => setExpanded(true), onMouseEnter: () => setShowPopover(true), onMouseLeave: () => setShowPopover(false), children: ["+", remainingCount, " more"] })), showPopover && !expanded && (_jsx("div", { className: "topics-popover", children: _jsx("div", { className: "topics-popover-grid", children: topics.map((t) => (_jsx("span", { className: "course-track-badge", children: t.Topic_Name }, t.Topic_ID))) }) }))] }), topics.length > 3 && (_jsx("button", { type: "button", className: "course-view-btn", onClick: () => setExpanded((e) => !e), "aria-label": expanded ? "Show less topics" : "View all topics", children: expanded ? "Show Less" : "View All Topics" })), _jsx("div", { className: "course-card-footer", children: _jsxs("span", { className: "course-last-updated", children: ["Updated ", course.Last_Updated] }) })] }));
};
export default CourseCard;
