export const mockCourses = [
    {
        Course_ID: 1,
        Course_Name: "Operating Systems",
        Max_Attempt: 3,
        Inst_ID: 2,
        Track_Name: "Computer Science",
        Students_Count: 45,
        Exams_Count: 8,
        Last_Updated: "2026-01-28",
    },
    {
        Course_ID: 2,
        Course_Name: "Data Structures",
        Max_Attempt: 3,
        Inst_ID: 2,
        Track_Name: "Computer Science",
        Students_Count: 52,
        Exams_Count: 12,
        Last_Updated: "2026-01-30",
    },
    {
        Course_ID: 3,
        Course_Name: "Algorithms",
        Max_Attempt: 4,
        Inst_ID: 2,
        Track_Name: "Computer Science",
        Students_Count: 38,
        Exams_Count: 10,
        Last_Updated: "2026-02-01",
    },
    {
        Course_ID: 4,
        Course_Name: "Database Systems",
        Max_Attempt: 3,
        Inst_ID: 2,
        Track_Name: "Software Engineering",
        Students_Count: 48,
        Exams_Count: 9,
        Last_Updated: "2026-01-25",
    },
    {
        Course_ID: 5,
        Course_Name: "Web Development",
        Max_Attempt: 3,
        Inst_ID: 2,
        Track_Name: "Full Stack",
        Students_Count: 67,
        Exams_Count: 15,
        Last_Updated: "2026-02-02",
    },
    {
        Course_ID: 6,
        Course_Name: "Machine Learning",
        Max_Attempt: 3,
        Inst_ID: 2,
        Track_Name: "AI and Data Science",
        Students_Count: 41,
        Exams_Count: 6,
        Last_Updated: "2026-01-29",
    },
    {
        Course_ID: 7,
        Course_Name: "Network Security",
        Max_Attempt: 2,
        Inst_ID: 2,
        Track_Name: "Cybersecurity",
        Students_Count: 35,
        Exams_Count: 7,
        Last_Updated: "2026-01-27",
    },
    {
        Course_ID: 8,
        Course_Name: "Mobile App Development",
        Max_Attempt: 3,
        Inst_ID: 2,
        Track_Name: "Mobile Development",
        Students_Count: 44,
        Exams_Count: 11,
        Last_Updated: "2026-02-01",
    },
    {
        Course_ID: 9,
        Course_Name: "Cloud Computing",
        Max_Attempt: 3,
        Inst_ID: 2,
        Track_Name: "DevOps",
        Students_Count: 39,
        Exams_Count: 5,
        Last_Updated: "2026-01-31",
    },
    {
        Course_ID: 10,
        Course_Name: "Software Engineering",
        Max_Attempt: 3,
        Inst_ID: 2,
        Track_Name: "Software Engineering",
        Students_Count: 56,
        Exams_Count: 13,
        Last_Updated: "2026-02-03",
    },
];
